name: Build WeChatAutoLogin
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

env:
  VERSION: '2.0.0'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Procursus Bootstrap (install)
        run: |
          wget https://apt.procurs.us/bootstraps/big_sur/bootstrap-darwin-amd64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap-darwin-amd64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V full-upgrade -y --allow-downgrades -oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confnew 
        continue-on-error: true

      - name: Set env
        run: |
          sT=$(TZ=UTC-8 date +'%S')
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.logT }}
          
      - name: Upgrade
        run: |
          sudo /opt/procursus/bin/apt -V upgrade -y --allow-downgrades -oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confnew
    
      - name: Upgrade and install
        run: |
          sudo /opt/procursus/bin/apt install zstd apt-utils ldid xz-utils bzip2 lz4 -y --allow-downgrades -oDpkg::Options::=--force-confdef -oDpkg::Options::=--force-confnew
        
      - name: Add Procursus to PATH
        run: |
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH

      - name: Select Correct Xcode (14.2)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app

      - name: Pre body
        run: |
          echo -e "\n更新时间：${{ env.logT }}" >> body.txt
          echo -e "\n**当前更新日志如下：**" >> body.txt
          echo -e "\n> - 同步官方最新2.5，汉化中文本地语言包" >> body.txt

      - name: Build Sileo
        run: |
          make clean package NIGHTLY=1 DEBUG=0 ALL_BOOTSTRAPS=1 SILEO_PLATFORM=iphoneos-arm64

      - name: Release deb
        uses: softprops/action-gh-release@v1
        with:
          name: sileo_${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          target_commitish: main
          body_path: body.txt
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           packages/*.deb
